name 'jmcdonagh/clamav'
version '0.99'
author 'Joe McDonagh <jmcdonagh@thesilentpenguin.com>'
summary 'ClamAV module'
description 'This module is for configuring Clam Anti-Virus'
license 'The license the module is release under the MIT License'
project_page 'http://www.thesilentpenguin.com/'
